auth_project/models.py
from auth_project import db,login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key=True)
    first_name = db.Column(db.String(30),nullable=False)
    last_name = db.Column(db.String(30),nullable=False)
    email = db.Column(db.String(130),unique=True,nullable=False)
    username = db.Column(db.String(30),nullable=False,unique=True)
    password = db.Column(db.String(80),nullable=False)

    def __repr__(self):
        return f'User({self.first_name} {self.last_name})'

auth_project/__init__.py
import os
from flask import Flask
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

app = Flask(__name__)
db = SQLAlchemy(app)
migrate = Migrate(app,db)
bcrypt = Bcrypt(app)
login_manager = LoginManager(app)
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('SQLALCHEMY_DATABASE_URI') 
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = os.environ.get('SQLALCHEMY_TRACK_MODIFICATIONS') or True
app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')

from .pages import pages as pagesblueprint
app.register_blueprint(pagesblueprint)
from .auth import auth as authBlueprint
app.register_blueprint(authBlueprint)

from . import app

auth_project/pages/__init__.py
from flask import Blueprint

pages = Blueprint('pages',__name__)

from . import routes

auth_project/pages/routes.py
from . import pages
from flask import render_template

@pages.route('/')
def home():
    return render_template('pages/home.html')

@pages.route('/about')
def about():
    return render_template('pages/about.html')

auth_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Authentication</title>{% endblock title %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/styles.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    {% include 'layouts/navbar.html' %}
    {% include 'layouts/messages.html' %}
    {% block content %}

    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{{ url_for('static',filename='js/main.js')}}"></script>
</body>
</html>

auth_project/templates/layouts/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category,message in messages %}
        <div class="alert alert-{{category}} alert-dismissible fade show" style="width: 45%;margin: auto;" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith%}

auth_project/templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('pages.home') }}">Authentication</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav m-auto">
          <a class="nav-link" href="{{ url_for('pages.home') }}">Home</a>
          <a class="nav-link" href="{{ url_for('pages.about') }}">About</a>
        </div>
        <div class="navbar-nav mr-auto">
          {% if current_user.is_authenticated %}
          <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          {% else %}
          <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          <a class="nav-link" href="{{ url_for('auth.register') }}">Signup</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>

auth_project/templates/pages/about.html
{% extends 'base.html' %}
{% block title %} <title>About</title> {% endblock title %}

{% block content %}
<h1>About</h1>
{% endblock content %}

auth_project/templates/pages/home.html
{% extends 'base.html' %}
{% block title %} <title>HomePage</title> {% endblock title %}

{% block content %}
<h1>Welcome</h1>
{% endblock content %}